[tasks.build]
description = "Build web app"
run = "npm run build"

[tasks.dev]
description = "Run in dev mode"
run = "npm run dev"
depends = ["//packages/image-uploader:build", "//packages/drawer-menu:build"]

[tasks.start]
description = "Start web app"
run = "npm run start"

[tasks.typecheck]
description = "Typecheck"
run = "npm run typecheck"

[env]
APP_HOST = "localhost"
API_URL = "http://localhost:8090"
PUBLIC_API_URL = "http://localhost:8090"
KEYSTONE_BASE_URL = "http://localhost:3002"
KEYSTONE_GRAPHQL_ENDPOINT = "http://localhost:3002/api/graphql"
KEYSTONE_API_USER_EMAIL = "example@example.com"
KEYSTONE_API_USER_PASSWORD = "123456abcdef"
