services:
  api:
    build:
      context: ./apps/api
      dockerfile: ./Dockerfile
    volumes:
      - ../files/pb_data:/app/pb_data

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        APP_NAME: ${APP_NAME:-App Name}
        APP_LANGUAGE: ${APP_LANGUAGE:-en}
        APP_PORT: ${APP_PORT:-3000}
        KEYSTONE_GRAPHQL_ENDPOINT: ${KEYSTONE_GRAPHQL_ENDPOINT:-http://localhost:3002/api/graphql}
    environment:
      API_URL: ${API_URL:-http://api:8080}
      PUBLIC_API_URL: ${PUBLIC_API_URL:-http://localhost:8080}
      KEYSTONE_GRAPHQL_ENDPOINT: ${KEYSTONE_GRAPHQL_ENDPOINT:-http://localhost:3002/api/graphql}

  keystone:
    build:
      context: .
      dockerfile: ./apps/keystone/Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ../files/keystone-data:/app/apps/keystone/data
      - ../files/keystone-assets:/app/apps/keystone/assets