[tasks.build]
description = "Build web app"
run = "npm run build"

[tasks.dev]
description = "Run in dev mode"
run = "npm run dev"

[tasks.start]
description = "Start keystone"
run = "npm run start"

[env]
_.file = '.env'